complete refactoring of with_xxx command helpers

diff --git a/with_utimaco b/with_utimaco
--- a/with_utimaco
+++ b/with_utimaco
@@ -37,30 +37,21 @@
 #
 # Note that SPY mode does not support NSS.
 
-PKCS11SLOT=0
-# no PKCS11PASSWORD set
+PKCS11PASSWORD=${PKCS11PASSWORD:-changeit}
 
 #specific to vendor
-case $(uname -s) in
-    Darwin)
-	PKCS11_LIBNAME=libbeidpkcs11.dylib
-	;;
-    *)
-	PKCS11_LIBNAME=libbeidpkcs11.so
-	;;
-esac
-PKCS11_LIBPATHS=( /usr/lib /usr/lib/$(uname -m)-linux-gnu /usr/local/lib /usr/local/lib/pkcs11 )
+PKCS11_LIBNAME=libcs_pkcs11_R2.so
+PKCS11_LIBPATHS=( /usr/lib /usr/local/lib /opt/utimaco/lib )
+LIB_ENVVARS=( CS_PKCS11_R2_CFG )
 
-LIB_ENVVARS=()
-
-########################################################################
-
-# find_p11_lib: a trivial function to find a library.
-function find_p11_lib()
+# setup of CS_PKCS11_R2_CFG
+# we expect to find it in /opt/utimaco/cs_pkcs11_R2.cfg, or
+#                      in /usr/local/etc/cs_pkcs11_R2.cfg
+function find_utimaco_cfg_file()
 {
-    lib=${PKCS11_LIBNAME}
-    paths=${PKCS11_LIBPATHS[@]}
-
+    file=cs_pkcs11_R2.cfg               
+    paths=( /opt/utimaco /usr/local/etc $HOME/utimaco/pkcs11 $HOME/utimaco )	# possible locations
+    
     for path in ${paths[@]}; do
 	if [ -e $path/$lib ]; then
 	    echo $path/$lib
@@ -72,12 +63,20 @@ function find_p11_lib()
     return 1
 }
 
-# find a configuration file, provided a file name and paths
-function find_cfg_file()
+CS_PKCS11_R2_CFG=${CS_PKCS11_R2_CFG:-$(find_utimaco_cfg_file)}
+if [ "$CS_PKCS11_R2_CFG" == "NOT FOUND" ]; then
+    echo "***Error: Utimaco configuration file not found, please set CS_PKCS11_R2_CFG accordingly."
+    exit 1
+fi
+
+########################################################################
+
+# find_p11_lib: a trivial function to find a library.
+function find_p11_lib()
 {
-    file=$1			# file name in $1
-    paths=${@:2}		# paths is an array ($2, $3, ...)
-    
+    lib=${PKCS11_LIBNAME}
+    paths=${PKCS11_LIBPATHS[@]}
+
     for path in ${paths[@]}; do
 	if [ -e $path/$lib ]; then
 	    echo $path/$lib
@@ -211,4 +210,3 @@ done
 
 eval ${environment[@]} ${quoted[@]}
 exit $?
-
